In [1]:
from google.colab import files
uploaded = files.upload()

Saving Dataset 2.csv to Dataset 2.csv

Q1. Load dataset and display first 5 records

In [2]:
import pandas as pd

df = pd.read_csv('Dataset 2.csv')

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

Q2. Number of rows and columns

In [3]:
print("Rows and Columns:", df.shape)

Rows and Columns: (750, 10)

Q3. Display all column names

In [4]:
print(df.columns)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

Q4. Numerical and categorical features

In [5]:
print("Numerical Columns:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("\nCategorical Columns:")
print(df.select_dtypes(include=['object']).columns)

Numerical Columns:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Columns:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

Q5. Check missing values

In [6]:
print(df.isnull().sum())

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

Q6. Average age

In [7]:
print("Average Age:", df['Age'].mean())

Average Age: 41.824

Q7. Average watch hours

In [8]:
print("Average Watch Hours:", df['WatchHoursPerWeek'].mean())

Average Watch Hours: 14.236

Q8. Average monthly spending

In [9]:
print("Average Monthly Spend:", df['MonthlySpend'].mean())

Average Monthly Spend: 689.9053333333334

Q9. Users in each subscription category

In [10]:
print(df['SubscriptionType'].value_counts())

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

Q10. Percentage of users who renewed

In [11]:
renewed = (df['SubscriptionRenewed'] == 'Yes').mean()*100

print("Renewal Percentage:", renewed)

Renewal Percentage: 46.266666666666666

Q11. Convert categorical features

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = ['Gender',
                    'SubscriptionType',
                    'FavoriteGenre',
                    'SubscriptionRenewed']

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

Q12. Define X and y

In [13]:
X = df.drop(['SubscriptionRenewed','UserID'], axis=1)

y = df['SubscriptionRenewed']

Q13. Split training and testing data

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Q14. Train model

In [15]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

Q15. Accuracy

In [16]:
from sklearn.metrics import accuracy_score

y_pred = dt.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Decision Tree Accuracy:", accuracy)

Decision Tree Accuracy: 0.56

Q16. Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[48 34]
 [32 36]]

Q17. Train KNN (K=5)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

Q18. Compare Accuracy

In [19]:
knn_acc = accuracy_score(y_test, knn_pred)

print("Decision Tree Accuracy:", accuracy)

print("KNN Accuracy:", knn_acc)

Decision Tree Accuracy: 0.56
KNN Accuracy: 0.6333333333333333

Q19. Train Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression

X_reg = df.drop(['MonthlySpend','UserID'], axis=1)

y_reg = df['MonthlySpend']

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

lr = LinearRegression()

lr.fit(X_train_reg, y_train_reg)

LinearRegression()

Q20. Predict Monthly Spending

In [21]:
new_user = [25,1,2,15,2,1,5,1]

prediction = lr.predict([new_user])

print("Predicted Monthly Spend:", prediction[0])

Predicted Monthly Spend: 1316.965643325569

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(